package:
  name: "chorus"
  version: "1.0.2"
  type: "binary"
  architecture: "x86_64"
  description: "Alternative build system written in Go"
  maintainer: "APGer <anmitali198@gmail.com>"
  license: "MIT"
  homepage: "https://github.com/z3nnix/chorus"
  tags: ["build", "system", "go"]
  dependencies: []
  conflicts: []
  provides: []
  replaces: []
  conf: []

source:
  url: "https://github.com/z3nnix/chorus/archive/refs/tags/{{VERSION}}.tar.gz"

build:
  dependencies: ["golang"]
  script: |
    export HOME=/tmp/home
    mkdir -p $HOME
    go build -o chorus.bin ./cmd/chorus

install:
  script: |
    mkdir -p "$DESTDIR/usr/bin"
    cp chorus.bin "$DESTDIR/usr/bin/chorus"
    chmod +x "$DESTDIR/usr/bin/chorus"
